/**
 * This class is generated by jOOQ
 */
package com.instructure.db.tables.records;


import com.instructure.db.tables.InstrSrvyDtls;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrSrvyDtlsRecord extends UpdatableRecordImpl<InstrSrvyDtlsRecord> implements Record4<Integer, String, Date, Date> {

    private static final long serialVersionUID = 1481916075;

    /**
     * Setter for <code>public.instr_srvy_dtls.srvy_id</code>.
     */
    public void setSrvyId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.instr_srvy_dtls.srvy_id</code>.
     */
    public Integer getSrvyId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.instr_srvy_dtls.srvy_name</code>.
     */
    public void setSrvyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.instr_srvy_dtls.srvy_name</code>.
     */
    public String getSrvyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.instr_srvy_dtls.srvy_strt_dt</code>.
     */
    public void setSrvyStrtDt(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.instr_srvy_dtls.srvy_strt_dt</code>.
     */
    public Date getSrvyStrtDt() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.instr_srvy_dtls.srvy_end_dt</code>.
     */
    public void setSrvyEndDt(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.instr_srvy_dtls.srvy_end_dt</code>.
     */
    public Date getSrvyEndDt() {
        return (Date) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Date, Date> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Date, Date> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InstrSrvyDtls.INSTR_SRVY_DTLS.SRVY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InstrSrvyDtls.INSTR_SRVY_DTLS.SRVY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return InstrSrvyDtls.INSTR_SRVY_DTLS.SRVY_STRT_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return InstrSrvyDtls.INSTR_SRVY_DTLS.SRVY_END_DT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSrvyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSrvyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getSrvyStrtDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getSrvyEndDt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtlsRecord value1(Integer value) {
        setSrvyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtlsRecord value2(String value) {
        setSrvyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtlsRecord value3(Date value) {
        setSrvyStrtDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtlsRecord value4(Date value) {
        setSrvyEndDt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtlsRecord values(Integer value1, String value2, Date value3, Date value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrSrvyDtlsRecord
     */
    public InstrSrvyDtlsRecord() {
        super(InstrSrvyDtls.INSTR_SRVY_DTLS);
    }

    /**
     * Create a detached, initialised InstrSrvyDtlsRecord
     */
    public InstrSrvyDtlsRecord(Integer srvyId, String srvyName, Date srvyStrtDt, Date srvyEndDt) {
        super(InstrSrvyDtls.INSTR_SRVY_DTLS);

        set(0, srvyId);
        set(1, srvyName);
        set(2, srvyStrtDt);
        set(3, srvyEndDt);
    }
}
