/**
 * This class is generated by jOOQ
 */
package jooq.codgen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.codgen.tables.InstrSrvyDtls;
import jooq.codgen.tables.InstrSrvyQtnOpts;
import jooq.codgen.tables.InstrSrvyQtns;
import jooq.codgen.tables.InstrUsrDtls;
import jooq.codgen.tables.InstrUsrSrvyMpng;
import jooq.codgen.tables.InstrUsrSrvyQtnOpt;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1284806937;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.instr_srvy_dtls</code>.
     */
    public final InstrSrvyDtls INSTR_SRVY_DTLS = jooq.codgen.tables.InstrSrvyDtls.INSTR_SRVY_DTLS;

    /**
     * The table <code>public.instr_srvy_qtn_opts</code>.
     */
    public final InstrSrvyQtnOpts INSTR_SRVY_QTN_OPTS = jooq.codgen.tables.InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS;

    /**
     * The table <code>public.instr_srvy_qtns</code>.
     */
    public final InstrSrvyQtns INSTR_SRVY_QTNS = jooq.codgen.tables.InstrSrvyQtns.INSTR_SRVY_QTNS;

    /**
     * The table <code>public.instr_usr_dtls</code>.
     */
    public final InstrUsrDtls INSTR_USR_DTLS = jooq.codgen.tables.InstrUsrDtls.INSTR_USR_DTLS;

    /**
     * The table <code>public.instr_usr_srvy_mpng</code>.
     */
    public final InstrUsrSrvyMpng INSTR_USR_SRVY_MPNG = jooq.codgen.tables.InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG;

    /**
     * The table <code>public.instr_usr_srvy_qtn_opt</code>.
     */
    public final InstrUsrSrvyQtnOpt INSTR_USR_SRVY_QTN_OPT = jooq.codgen.tables.InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.INSTR_USR_SRVY_QTN_OPT_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            InstrSrvyDtls.INSTR_SRVY_DTLS,
            InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS,
            InstrSrvyQtns.INSTR_SRVY_QTNS,
            InstrUsrDtls.INSTR_USR_DTLS,
            InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG,
            InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT);
    }
}
