/**
 * This class is generated by jOOQ
 */
package jooq.codgen;


import javax.annotation.Generated;

import jooq.codgen.tables.InstrSrvyDtls;
import jooq.codgen.tables.InstrSrvyQtnOpts;
import jooq.codgen.tables.InstrSrvyQtns;
import jooq.codgen.tables.InstrUsrDtls;
import jooq.codgen.tables.InstrUsrSrvyMpng;
import jooq.codgen.tables.InstrUsrSrvyQtnOpt;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.instr_srvy_dtls</code>.
     */
    public static final InstrSrvyDtls INSTR_SRVY_DTLS = jooq.codgen.tables.InstrSrvyDtls.INSTR_SRVY_DTLS;

    /**
     * The table <code>public.instr_srvy_qtn_opts</code>.
     */
    public static final InstrSrvyQtnOpts INSTR_SRVY_QTN_OPTS = jooq.codgen.tables.InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS;

    /**
     * The table <code>public.instr_srvy_qtns</code>.
     */
    public static final InstrSrvyQtns INSTR_SRVY_QTNS = jooq.codgen.tables.InstrSrvyQtns.INSTR_SRVY_QTNS;

    /**
     * The table <code>public.instr_usr_dtls</code>.
     */
    public static final InstrUsrDtls INSTR_USR_DTLS = jooq.codgen.tables.InstrUsrDtls.INSTR_USR_DTLS;

    /**
     * The table <code>public.instr_usr_srvy_mpng</code>.
     */
    public static final InstrUsrSrvyMpng INSTR_USR_SRVY_MPNG = jooq.codgen.tables.InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG;

    /**
     * The table <code>public.instr_usr_srvy_qtn_opt</code>.
     */
    public static final InstrUsrSrvyQtnOpt INSTR_USR_SRVY_QTN_OPT = jooq.codgen.tables.InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT;
}
