/**
 * This class is generated by jOOQ
 */
package jooq.codgen.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import jooq.codgen.tables.InstrUsrSrvyQtnOpt;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrUsrSrvyQtnOptRecord extends UpdatableRecordImpl<InstrUsrSrvyQtnOptRecord> implements Record8<Integer, Integer, Integer, String, String, Date, Date, Integer> {

    private static final long serialVersionUID = -205248471;

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.usr_srvy_qtn_opt_id</code>.
     */
    public void setUsrSrvyQtnOptId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.usr_srvy_qtn_opt_id</code>.
     */
    public Integer getUsrSrvyQtnOptId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_id</code>.
     */
    public void setSrvyQtnId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_id</code>.
     */
    public Integer getSrvyQtnId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_opt_id</code>.
     */
    public void setSrvyQtnOptId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_opt_id</code>.
     */
    public Integer getSrvyQtnOptId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.crtd_usr</code>.
     */
    public void setCrtdUsr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.crtd_usr</code>.
     */
    public String getCrtdUsr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.lst_updtd_usr</code>.
     */
    public void setLstUpdtdUsr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.lst_updtd_usr</code>.
     */
    public String getLstUpdtdUsr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.crtd_time</code>.
     */
    public void setCrtdTime(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.crtd_time</code>.
     */
    public Date getCrtdTime() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.lst_updtd_time</code>.
     */
    public void setLstUpdtdTime(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.lst_updtd_time</code>.
     */
    public Date getLstUpdtdTime() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>public.instr_usr_srvy_qtn_opt.usr_srvy_mpng_id</code>.
     */
    public void setUsrSrvyMpngId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.instr_usr_srvy_qtn_opt.usr_srvy_mpng_id</code>.
     */
    public Integer getUsrSrvyMpngId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, String, Date, Date, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, String, Date, Date, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.USR_SRVY_QTN_OPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.SRVY_QTN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.SRVY_QTN_OPT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.CRTD_USR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.LST_UPDTD_USR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.CRTD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.LST_UPDTD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.USR_SRVY_MPNG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUsrSrvyQtnOptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSrvyQtnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSrvyQtnOptId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtdUsr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLstUpdtdUsr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getCrtdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getLstUpdtdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getUsrSrvyMpngId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value1(Integer value) {
        setUsrSrvyQtnOptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value2(Integer value) {
        setSrvyQtnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value3(Integer value) {
        setSrvyQtnOptId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value4(String value) {
        setCrtdUsr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value5(String value) {
        setLstUpdtdUsr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value6(Date value) {
        setCrtdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value7(Date value) {
        setLstUpdtdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord value8(Integer value) {
        setUsrSrvyMpngId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOptRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Date value6, Date value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrUsrSrvyQtnOptRecord
     */
    public InstrUsrSrvyQtnOptRecord() {
        super(InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT);
    }

    /**
     * Create a detached, initialised InstrUsrSrvyQtnOptRecord
     */
    public InstrUsrSrvyQtnOptRecord(Integer usrSrvyQtnOptId, Integer srvyQtnId, Integer srvyQtnOptId, String crtdUsr, String lstUpdtdUsr, Date crtdTime, Date lstUpdtdTime, Integer usrSrvyMpngId) {
        super(InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT);

        set(0, usrSrvyQtnOptId);
        set(1, srvyQtnId);
        set(2, srvyQtnOptId);
        set(3, crtdUsr);
        set(4, lstUpdtdUsr);
        set(5, crtdTime);
        set(6, lstUpdtdTime);
        set(7, usrSrvyMpngId);
    }
}
