/**
 * This class is generated by jOOQ
 */
package jooq.codgen.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.codgen.Keys;
import jooq.codgen.Public;
import jooq.codgen.tables.records.InstrSrvyQtnsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrSrvyQtns extends TableImpl<InstrSrvyQtnsRecord> {

    private static final long serialVersionUID = -1068681414;

    /**
     * The reference instance of <code>public.instr_srvy_qtns</code>
     */
    public static final InstrSrvyQtns INSTR_SRVY_QTNS = new InstrSrvyQtns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstrSrvyQtnsRecord> getRecordType() {
        return InstrSrvyQtnsRecord.class;
    }

    /**
     * The column <code>public.instr_srvy_qtns.srvy_qtn_id</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, Integer> SRVY_QTN_ID = createField("srvy_qtn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtns.srvy_id</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, Integer> SRVY_ID = createField("srvy_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtns.qtn_txt</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, String> QTN_TXT = createField("qtn_txt", org.jooq.impl.SQLDataType.VARCHAR.length(2000).nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtns.crtd_usr</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, String> CRTD_USR = createField("crtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_srvy_qtns.lst_updtd_usr</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, String> LST_UPDTD_USR = createField("lst_updtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_srvy_qtns.crtd_time</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, Date> CRTD_TIME = createField("crtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.instr_srvy_qtns.lst_updtd_time</code>.
     */
    public final TableField<InstrSrvyQtnsRecord, Date> LST_UPDTD_TIME = createField("lst_updtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>public.instr_srvy_qtns</code> table reference
     */
    public InstrSrvyQtns() {
        this("instr_srvy_qtns", null);
    }

    /**
     * Create an aliased <code>public.instr_srvy_qtns</code> table reference
     */
    public InstrSrvyQtns(String alias) {
        this(alias, INSTR_SRVY_QTNS);
    }

    private InstrSrvyQtns(String alias, Table<InstrSrvyQtnsRecord> aliased) {
        this(alias, aliased, null);
    }

    private InstrSrvyQtns(String alias, Table<InstrSrvyQtnsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstrSrvyQtnsRecord> getPrimaryKey() {
        return Keys.INSTR_SRVY_QTNS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstrSrvyQtnsRecord>> getKeys() {
        return Arrays.<UniqueKey<InstrSrvyQtnsRecord>>asList(Keys.INSTR_SRVY_QTNS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InstrSrvyQtnsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InstrSrvyQtnsRecord, ?>>asList(Keys.INSTR_SRVY_QTNS__INSTR_SRVY_QTNS_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtns as(String alias) {
        return new InstrSrvyQtns(alias, this);
    }

    /**
     * Rename this table
     */
    public InstrSrvyQtns rename(String name) {
        return new InstrSrvyQtns(name, null);
    }
}
