/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity;


import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyDtls;
import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyQtnOpts;
import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyQtns;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrDtls;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrSrvyMpng;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrSrvyQtnOpt;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrSrvyDtlsRecord;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrSrvyQtnOptsRecord;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrSrvyQtnsRecord;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrUsrDtlsRecord;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrUsrSrvyMpngRecord;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrUsrSrvyQtnOptRecord;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InstrSrvyDtlsRecord> INSTR_SRVY_TLS_PKEY = UniqueKeys0.INSTR_SRVY_TLS_PKEY;
    public static final UniqueKey<InstrSrvyQtnOptsRecord> INSTR_SRVY_QTN_OPTS_PKEY = UniqueKeys0.INSTR_SRVY_QTN_OPTS_PKEY;
    public static final UniqueKey<InstrSrvyQtnsRecord> INSTR_SRVY_QTNS_PKEY = UniqueKeys0.INSTR_SRVY_QTNS_PKEY;
    public static final UniqueKey<InstrUsrDtlsRecord> INSTR_USR_DTLS_PKEY = UniqueKeys0.INSTR_USR_DTLS_PKEY;
    public static final UniqueKey<InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_MPNG_PKEY = UniqueKeys0.INSTR_USR_SRVY_MPNG_PKEY;
    public static final UniqueKey<InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_MPNG_UK = UniqueKeys0.INSTR_USR_SRVY_MPNG_UK;
    public static final UniqueKey<InstrUsrSrvyQtnOptRecord> INSTR_USR_SRVY_QTN_OPT_PKEY = UniqueKeys0.INSTR_USR_SRVY_QTN_OPT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<InstrSrvyQtnOptsRecord, InstrSrvyQtnsRecord> INSTR_SRVY_QTN_OPTS__INSTR_SRVY_QTN_OPTS_FK = ForeignKeys0.INSTR_SRVY_QTN_OPTS__INSTR_SRVY_QTN_OPTS_FK;
    public static final ForeignKey<InstrSrvyQtnsRecord, InstrSrvyDtlsRecord> INSTR_SRVY_QTNS__INSTR_SRVY_QTNS_FK = ForeignKeys0.INSTR_SRVY_QTNS__INSTR_SRVY_QTNS_FK;
    public static final ForeignKey<InstrUsrSrvyMpngRecord, InstrUsrDtlsRecord> INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK1 = ForeignKeys0.INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK1;
    public static final ForeignKey<InstrUsrSrvyMpngRecord, InstrSrvyDtlsRecord> INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK2 = ForeignKeys0.INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK2;
    public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrSrvyQtnsRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK = ForeignKeys0.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK;
    public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrSrvyQtnOptsRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK1 = ForeignKeys0.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK1;
    public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK2 = ForeignKeys0.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<InstrSrvyDtlsRecord> INSTR_SRVY_TLS_PKEY = createUniqueKey(InstrSrvyDtls.INSTR_SRVY_DTLS, "instr_srvy_tls_pkey", InstrSrvyDtls.INSTR_SRVY_DTLS.SRVY_ID);
        public static final UniqueKey<InstrSrvyQtnOptsRecord> INSTR_SRVY_QTN_OPTS_PKEY = createUniqueKey(InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS, "instr_srvy_qtn_opts_pkey", InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS.SRVY_QTN_OPT_ID);
        public static final UniqueKey<InstrSrvyQtnsRecord> INSTR_SRVY_QTNS_PKEY = createUniqueKey(InstrSrvyQtns.INSTR_SRVY_QTNS, "instr_srvy_qtns_pkey", InstrSrvyQtns.INSTR_SRVY_QTNS.SRVY_QTN_ID);
        public static final UniqueKey<InstrUsrDtlsRecord> INSTR_USR_DTLS_PKEY = createUniqueKey(InstrUsrDtls.INSTR_USR_DTLS, "instr_usr_dtls_pkey", InstrUsrDtls.INSTR_USR_DTLS.USER_ID);
        public static final UniqueKey<InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_MPNG_PKEY = createUniqueKey(InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG, "instr_usr_srvy_mpng_pkey", InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG.USR_SRVY_MPNG_ID);
        public static final UniqueKey<InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_MPNG_UK = createUniqueKey(InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG, "instr_usr_Srvy_mpng_uk", InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG.USR_ID, InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG.SRVY_ID);
        public static final UniqueKey<InstrUsrSrvyQtnOptRecord> INSTR_USR_SRVY_QTN_OPT_PKEY = createUniqueKey(InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT, "instr_usr_srvy_qtn_opt_pkey", InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.USR_SRVY_QTN_OPT_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<InstrSrvyQtnOptsRecord, InstrSrvyQtnsRecord> INSTR_SRVY_QTN_OPTS__INSTR_SRVY_QTN_OPTS_FK = createForeignKey(Keys.INSTR_SRVY_QTNS_PKEY, InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS, "instr_srvy_qtn_opts__instr_srvy_qtn_opts_fk", InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS.SRVY_QTN_ID);
        public static final ForeignKey<InstrSrvyQtnsRecord, InstrSrvyDtlsRecord> INSTR_SRVY_QTNS__INSTR_SRVY_QTNS_FK = createForeignKey(Keys.INSTR_SRVY_TLS_PKEY, InstrSrvyQtns.INSTR_SRVY_QTNS, "instr_srvy_qtns__instr_srvy_qtns_fk", InstrSrvyQtns.INSTR_SRVY_QTNS.SRVY_ID);
        public static final ForeignKey<InstrUsrSrvyMpngRecord, InstrUsrDtlsRecord> INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK1 = createForeignKey(Keys.INSTR_USR_DTLS_PKEY, InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG, "instr_usr_srvy_mpng__instr_usr_srvy_mpng_fk1", InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG.USR_ID);
        public static final ForeignKey<InstrUsrSrvyMpngRecord, InstrSrvyDtlsRecord> INSTR_USR_SRVY_MPNG__INSTR_USR_SRVY_MPNG_FK2 = createForeignKey(Keys.INSTR_SRVY_TLS_PKEY, InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG, "instr_usr_srvy_mpng__instr_usr_srvy_mpng_fk2", InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG.SRVY_ID);
        public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrSrvyQtnsRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK = createForeignKey(Keys.INSTR_SRVY_QTNS_PKEY, InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT, "instr_usr_srvy_qtn_opt__instr_usr_srvy_qtn_opt_fk", InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.SRVY_QTN_ID);
        public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrSrvyQtnOptsRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK1 = createForeignKey(Keys.INSTR_SRVY_QTN_OPTS_PKEY, InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT, "instr_usr_srvy_qtn_opt__instr_usr_srvy_qtn_opt_fk1", InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.SRVY_QTN_OPT_ID);
        public static final ForeignKey<InstrUsrSrvyQtnOptRecord, InstrUsrSrvyMpngRecord> INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK2 = createForeignKey(Keys.INSTR_USR_SRVY_MPNG_PKEY, InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT, "instr_usr_srvy_qtn_opt__instr_usr_srvy_qtn_opt_fk2", InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT.USR_SRVY_MPNG_ID);
    }
}
