/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.instr_usr_srvy_qtn_opt_seq</code>
     */
    public static final Sequence<Long> INSTR_USR_SRVY_QTN_OPT_SEQ = new SequenceImpl<Long>("instr_usr_srvy_qtn_opt_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
