/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity;


import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyDtls;
import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyQtnOpts;
import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyQtns;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrDtls;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrSrvyMpng;
import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrSrvyQtnOpt;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.instr_srvy_dtls</code>.
     */
    public static final InstrSrvyDtls INSTR_SRVY_DTLS = InstrSrvyDtls.INSTR_SRVY_DTLS;

    /**
     * The table <code>public.instr_srvy_qtn_opts</code>.
     */
    public static final InstrSrvyQtnOpts INSTR_SRVY_QTN_OPTS = InstrSrvyQtnOpts.INSTR_SRVY_QTN_OPTS;

    /**
     * The table <code>public.instr_srvy_qtns</code>.
     */
    public static final InstrSrvyQtns INSTR_SRVY_QTNS = InstrSrvyQtns.INSTR_SRVY_QTNS;

    /**
     * The table <code>public.instr_usr_dtls</code>.
     */
    public static final InstrUsrDtls INSTR_USR_DTLS = InstrUsrDtls.INSTR_USR_DTLS;

    /**
     * The table <code>public.instr_usr_srvy_mpng</code>.
     */
    public static final InstrUsrSrvyMpng INSTR_USR_SRVY_MPNG = InstrUsrSrvyMpng.INSTR_USR_SRVY_MPNG;

    /**
     * The table <code>public.instr_usr_srvy_qtn_opt</code>.
     */
    public static final InstrUsrSrvyQtnOpt INSTR_USR_SRVY_QTN_OPT = InstrUsrSrvyQtnOpt.INSTR_USR_SRVY_QTN_OPT;
}
