/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.tables.InstrSrvyQtns;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrSrvyQtnsRecord extends UpdatableRecordImpl<InstrSrvyQtnsRecord> implements Record7<Integer, Integer, String, String, String, Date, Date> {

    private static final long serialVersionUID = 123109344;

    /**
     * Setter for <code>public.instr_srvy_qtns.srvy_qtn_id</code>.
     */
    public void setSrvyQtnId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.srvy_qtn_id</code>.
     */
    public Integer getSrvyQtnId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.srvy_id</code>.
     */
    public void setSrvyId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.srvy_id</code>.
     */
    public Integer getSrvyId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.qtn_txt</code>.
     */
    public void setQtnTxt(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.qtn_txt</code>.
     */
    public String getQtnTxt() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.crtd_usr</code>.
     */
    public void setCrtdUsr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.crtd_usr</code>.
     */
    public String getCrtdUsr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.lst_updtd_usr</code>.
     */
    public void setLstUpdtdUsr(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.lst_updtd_usr</code>.
     */
    public String getLstUpdtdUsr() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.crtd_time</code>.
     */
    public void setCrtdTime(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.crtd_time</code>.
     */
    public Date getCrtdTime() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.instr_srvy_qtns.lst_updtd_time</code>.
     */
    public void setLstUpdtdTime(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.instr_srvy_qtns.lst_updtd_time</code>.
     */
    public Date getLstUpdtdTime() {
        return (Date) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Date, Date> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Date, Date> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.SRVY_QTN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.SRVY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.QTN_TXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.CRTD_USR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.LST_UPDTD_USR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.CRTD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return InstrSrvyQtns.INSTR_SRVY_QTNS.LST_UPDTD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSrvyQtnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSrvyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getQtnTxt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrtdUsr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLstUpdtdUsr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getCrtdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getLstUpdtdTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value1(Integer value) {
        setSrvyQtnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value2(Integer value) {
        setSrvyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value3(String value) {
        setQtnTxt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value4(String value) {
        setCrtdUsr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value5(String value) {
        setLstUpdtdUsr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value6(Date value) {
        setCrtdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord value7(Date value) {
        setLstUpdtdTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnsRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Date value6, Date value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrSrvyQtnsRecord
     */
    public InstrSrvyQtnsRecord() {
        super(InstrSrvyQtns.INSTR_SRVY_QTNS);
    }

    /**
     * Create a detached, initialised InstrSrvyQtnsRecord
     */
    public InstrSrvyQtnsRecord(Integer srvyQtnId, Integer srvyId, String qtnTxt, String crtdUsr, String lstUpdtdUsr, Date crtdTime, Date lstUpdtdTime) {
        super(InstrSrvyQtns.INSTR_SRVY_QTNS);

        set(0, srvyQtnId);
        set(1, srvyId);
        set(2, qtnTxt);
        set(3, crtdUsr);
        set(4, lstUpdtdUsr);
        set(5, crtdTime);
        set(6, lstUpdtdTime);
    }
}
