/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity.tables.records;


import com.instructure.bridge.survey.adapter.entity.tables.InstrUsrDtls;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrUsrDtlsRecord extends UpdatableRecordImpl<InstrUsrDtlsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 420045638;

    /**
     * Setter for <code>public.instr_usr_dtls.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.instr_usr_dtls.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.instr_usr_dtls.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.instr_usr_dtls.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InstrUsrDtls.INSTR_USR_DTLS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InstrUsrDtls.INSTR_USR_DTLS.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrDtlsRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrDtlsRecord value2(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrDtlsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstrUsrDtlsRecord
     */
    public InstrUsrDtlsRecord() {
        super(InstrUsrDtls.INSTR_USR_DTLS);
    }

    /**
     * Create a detached, initialised InstrUsrDtlsRecord
     */
    public InstrUsrDtlsRecord(Integer userId, String userName) {
        super(InstrUsrDtls.INSTR_USR_DTLS);

        set(0, userId);
        set(1, userName);
    }
}
