/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity.tables;


import com.instructure.bridge.survey.adapter.entity.tables.records.InstrSrvyQtnOptsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.Keys;
import com.instructure.bridge.survey.adapter.entity.Public;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrSrvyQtnOpts extends TableImpl<InstrSrvyQtnOptsRecord> {

    private static final long serialVersionUID = -1210516247;

    /**
     * The reference instance of <code>public.instr_srvy_qtn_opts</code>
     */
    public static final InstrSrvyQtnOpts INSTR_SRVY_QTN_OPTS = new InstrSrvyQtnOpts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstrSrvyQtnOptsRecord> getRecordType() {
        return InstrSrvyQtnOptsRecord.class;
    }

    /**
     * The column <code>public.instr_srvy_qtn_opts.srvy_qtn_opt_id</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, Integer> SRVY_QTN_OPT_ID = createField("srvy_qtn_opt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.srvy_qtn_id</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, Integer> SRVY_QTN_ID = createField("srvy_qtn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.opt_text</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, String> OPT_TEXT = createField("opt_text", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.crtd_usr</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, String> CRTD_USR = createField("crtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.lst_updtd_usr</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, String> LST_UPDTD_USR = createField("lst_updtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.crtd_time</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, Date> CRTD_TIME = createField("crtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.instr_srvy_qtn_opts.lst_updtd_time</code>.
     */
    public final TableField<InstrSrvyQtnOptsRecord, Date> LST_UPDTD_TIME = createField("lst_updtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>public.instr_srvy_qtn_opts</code> table reference
     */
    public InstrSrvyQtnOpts() {
        this("instr_srvy_qtn_opts", null);
    }

    /**
     * Create an aliased <code>public.instr_srvy_qtn_opts</code> table reference
     */
    public InstrSrvyQtnOpts(String alias) {
        this(alias, INSTR_SRVY_QTN_OPTS);
    }

    private InstrSrvyQtnOpts(String alias, Table<InstrSrvyQtnOptsRecord> aliased) {
        this(alias, aliased, null);
    }

    private InstrSrvyQtnOpts(String alias, Table<InstrSrvyQtnOptsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstrSrvyQtnOptsRecord> getPrimaryKey() {
        return Keys.INSTR_SRVY_QTN_OPTS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstrSrvyQtnOptsRecord>> getKeys() {
        return Arrays.<UniqueKey<InstrSrvyQtnOptsRecord>>asList(Keys.INSTR_SRVY_QTN_OPTS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InstrSrvyQtnOptsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InstrSrvyQtnOptsRecord, ?>>asList(Keys.INSTR_SRVY_QTN_OPTS__INSTR_SRVY_QTN_OPTS_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyQtnOpts as(String alias) {
        return new InstrSrvyQtnOpts(alias, this);
    }

    /**
     * Rename this table
     */
    public InstrSrvyQtnOpts rename(String name) {
        return new InstrSrvyQtnOpts(name, null);
    }
}
