/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.Keys;
import com.instructure.bridge.survey.adapter.entity.Public;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrSrvyDtlsRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrSrvyDtls extends TableImpl<InstrSrvyDtlsRecord> {

    private static final long serialVersionUID = 323734871;

    /**
     * The reference instance of <code>public.instr_srvy_dtls</code>
     */
    public static final InstrSrvyDtls INSTR_SRVY_DTLS = new InstrSrvyDtls();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstrSrvyDtlsRecord> getRecordType() {
        return InstrSrvyDtlsRecord.class;
    }

    /**
     * The column <code>public.instr_srvy_dtls.srvy_id</code>.
     */
    public final TableField<InstrSrvyDtlsRecord, Integer> SRVY_ID = createField("srvy_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_dtls.srvy_name</code>.
     */
    public final TableField<InstrSrvyDtlsRecord, String> SRVY_NAME = createField("srvy_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_dtls.srvy_strt_dt</code>.
     */
    public final TableField<InstrSrvyDtlsRecord, Date> SRVY_STRT_DT = createField("srvy_strt_dt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.instr_srvy_dtls.srvy_end_dt</code>.
     */
    public final TableField<InstrSrvyDtlsRecord, Date> SRVY_END_DT = createField("srvy_end_dt", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>public.instr_srvy_dtls</code> table reference
     */
    public InstrSrvyDtls() {
        this("instr_srvy_dtls", null);
    }

    /**
     * Create an aliased <code>public.instr_srvy_dtls</code> table reference
     */
    public InstrSrvyDtls(String alias) {
        this(alias, INSTR_SRVY_DTLS);
    }

    private InstrSrvyDtls(String alias, Table<InstrSrvyDtlsRecord> aliased) {
        this(alias, aliased, null);
    }

    private InstrSrvyDtls(String alias, Table<InstrSrvyDtlsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstrSrvyDtlsRecord> getPrimaryKey() {
        return Keys.INSTR_SRVY_TLS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstrSrvyDtlsRecord>> getKeys() {
        return Arrays.<UniqueKey<InstrSrvyDtlsRecord>>asList(Keys.INSTR_SRVY_TLS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrSrvyDtls as(String alias) {
        return new InstrSrvyDtls(alias, this);
    }

    /**
     * Rename this table
     */
    public InstrSrvyDtls rename(String name) {
        return new InstrSrvyDtls(name, null);
    }
}
