/**
 * This class is generated by jOOQ
 */
package com.instructure.bridge.survey.adapter.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import com.instructure.bridge.survey.adapter.entity.Keys;
import com.instructure.bridge.survey.adapter.entity.Public;
import com.instructure.bridge.survey.adapter.entity.tables.records.InstrUsrSrvyQtnOptRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstrUsrSrvyQtnOpt extends TableImpl<InstrUsrSrvyQtnOptRecord> {

    private static final long serialVersionUID = 258577365;

    /**
     * The reference instance of <code>public.instr_usr_srvy_qtn_opt</code>
     */
    public static final InstrUsrSrvyQtnOpt INSTR_USR_SRVY_QTN_OPT = new InstrUsrSrvyQtnOpt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstrUsrSrvyQtnOptRecord> getRecordType() {
        return InstrUsrSrvyQtnOptRecord.class;
    }

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.usr_srvy_qtn_opt_id</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Integer> USR_SRVY_QTN_OPT_ID = createField("usr_srvy_qtn_opt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_id</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Integer> SRVY_QTN_ID = createField("srvy_qtn_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.srvy_qtn_opt_id</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Integer> SRVY_QTN_OPT_ID = createField("srvy_qtn_opt_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.crtd_usr</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, String> CRTD_USR = createField("crtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.lst_updtd_usr</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, String> LST_UPDTD_USR = createField("lst_updtd_usr", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.crtd_time</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Date> CRTD_TIME = createField("crtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.lst_updtd_time</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Date> LST_UPDTD_TIME = createField("lst_updtd_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>public.instr_usr_srvy_qtn_opt.usr_srvy_mpng_id</code>.
     */
    public final TableField<InstrUsrSrvyQtnOptRecord, Integer> USR_SRVY_MPNG_ID = createField("usr_srvy_mpng_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.instr_usr_srvy_qtn_opt</code> table reference
     */
    public InstrUsrSrvyQtnOpt() {
        this("instr_usr_srvy_qtn_opt", null);
    }

    /**
     * Create an aliased <code>public.instr_usr_srvy_qtn_opt</code> table reference
     */
    public InstrUsrSrvyQtnOpt(String alias) {
        this(alias, INSTR_USR_SRVY_QTN_OPT);
    }

    private InstrUsrSrvyQtnOpt(String alias, Table<InstrUsrSrvyQtnOptRecord> aliased) {
        this(alias, aliased, null);
    }

    private InstrUsrSrvyQtnOpt(String alias, Table<InstrUsrSrvyQtnOptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InstrUsrSrvyQtnOptRecord> getPrimaryKey() {
        return Keys.INSTR_USR_SRVY_QTN_OPT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InstrUsrSrvyQtnOptRecord>> getKeys() {
        return Arrays.<UniqueKey<InstrUsrSrvyQtnOptRecord>>asList(Keys.INSTR_USR_SRVY_QTN_OPT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InstrUsrSrvyQtnOptRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InstrUsrSrvyQtnOptRecord, ?>>asList(Keys.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK, Keys.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK1, Keys.INSTR_USR_SRVY_QTN_OPT__INSTR_USR_SRVY_QTN_OPT_FK2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstrUsrSrvyQtnOpt as(String alias) {
        return new InstrUsrSrvyQtnOpt(alias, this);
    }

    /**
     * Rename this table
     */
    public InstrUsrSrvyQtnOpt rename(String name) {
        return new InstrUsrSrvyQtnOpt(name, null);
    }
}
